



const quotes = [
    "Talk is cheap. Show me the code. - Linus Torvalds",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "Truth can only be found in one place: the code. - Robert C. Martin",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "Fix the cause, not the symptom. - Steve Maguire",
    "Optimism is an occupational hazard of programming: feedback is the treatment. - Kent Beck",
    "When to use iterative development? You should use iterative development only on projects that you want to succeed. - Martin Fowler",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "Before software can be reusable it first has to be usable. - Ralph Johnson",
    "Make it work, make it right, make it fast. - Kent Beck",
    "One man’s crappy software is another man’s full-time job. - Jessica Gaston",
    "Java is to JavaScript what car is to Carpet. - Chris Heilmann",
    "If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization. - Gerald Weinberg",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. - Seymour Cray",
    "Don’t worry if it doesn’t work right. If everything did, you’d be out of a job. - Mosher’s Law of Software Engineering",
    "The most disastrous thing that you can ever learn is your first programming language. - Alan Kay",
    "In order to be irreplaceable, one must always be different. - Coco Chanel",
    "You might not think that programmers are artists, but programming is an extremely creative profession. It’s logic-based creativity. - John Romero",
    "The function of good software is to make the complex appear to be simple. - Grady Booch",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "The only way to learn a new programming language is by writing programs in it. - Dennis Ritchie",
    "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code. - Dan Salomon",
    "Don’t comment bad code—rewrite it. - Brian W. Kernighan",
    "Testing leads to failure, and failure leads to understanding. - Burt Rutan",
    "The best method for accelerating a computer is the one that boosts it by 9.8 m/s². - Anonymous",
    "Even the best planning is not so omniscient as to get it right the first time. - Fred Brooks",
    "The hardest part of design is keeping features out. - Donald Norman",
    "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. - C.A.R. Hoare",
    "The computing scientist’s main challenge is not to get confused by the complexities of his own making. - Edsger W. Dijkstra",
    "Any sufficiently advanced bug is indistinguishable from a feature. - Rich Kulawiec",
    "Adding manpower to a late software project makes it later. - Fred Brooks",
    "First, solve the problem. Then, write the code. - John Johnson",
    "Good code is its own best documentation. - Steve McConnell",
    "Code never lies, comments sometimes do. - Ron Jeffries",
    "Experience is the name everyone gives to their mistakes. - Oscar Wilde",
    "The best error message is the one that never shows up. - Thomas Fuchs",
    "Deleted code is debugged code. - Jeff Sickel",
    "You can have the project: Done On Time. Done On Budget. Works Correctly—Pick two. - Anonymous",
    "A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
    "Programming can be fun, and so can cryptography; however, they should not be combined. - Kreitzberg and Shneiderman",
    "Copy-and-Paste was programmed by programmers for programmers actually. - Anonymous",
    "Programmers are tools for converting caffeine into code. - Anonymous",
    "A language that doesn’t affect the way you think about programming is not worth knowing. - Alan Perlis",
    "It’s not a bug – it’s an undocumented feature. - Anonymous",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "Software is like sex: It’s better when it’s free. - Linus Torvalds",
    "In software, the most beautiful code, the most beautiful functions, and the most beautiful programs are sometimes not there at all. - Jon Bentley",
    "Programming is the art of telling another human being what one wants the computer to do. - Donald Knuth",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "The best way to get a project done faster is to start sooner. - Jim Highsmith",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. - Niklaus Wirth",
    "To iterate is human, to recurse divine. - L. Peter Deutsch",
    "Weeks of coding can save you hours of planning. - Anonymous",
    "If you think your users are idiots, only idiots will use it. - Linus Torvalds",
    "The most important property of a program is whether it accomplishes the intention of its user. - C.A.R. Hoare",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "It’s OK to figure out murder mysteries, but you shouldn’t need to figure out code. You should be able to read it. - Steve McConnell",
    "Programming is like writing a book... except if you miss out a single comma on page 126 the whole thing makes no sense. - Anonymous",
    "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements. - Brian Kernighan",
    "One of the best programming skills you can have is knowing when to walk away for a while. - Oscar Godson",
    "No code has zero defects. - Wietse Venema",
    "If brute force doesn’t solve your problems, then you aren’t using enough. - Anonymous",
    "The only constant in programming is change. - Anonymous",
    "A computer is like a violin. You can imagine a novice trying first a phonograph and then a violin; there is no comparison in the sound, and no reason at all why a violin should sound better than a phonograph. Programming is the same: It is easy to use a computer poorly. - Marvin Minsky",
    "Programming languages, like pizzas, come in only one size: too big. - Richard Pattis",
    "The computer was born to solve problems that did not exist before. - Bill Gates",
    "The more code you have, the more places there are for bugs to hide. - Rich Skrenta",
    "If you can’t explain it simply, you don’t understand it well enough. - Albert Einstein",
    "Simplicity is prerequisite for reliability. - Edsger W. Dijkstra",
    "The problem is not that there are problems. The problem is expecting otherwise and thinking that having problems is a problem. - Theodore Rubin",
    "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it. - Brian Kernighan",
    "The proper use of comments is to compensate for our failure to express ourself in code. - Robert C. Martin",
    "When I wrote this code, only God and I understood what I did. Now only God knows. - Anonymous",
    "In programming the hard part isn’t solving problems, but deciding what problems to solve. - Paul Graham",
    "The key to performance is elegance, not battalions of special cases. - Jon Bentley and Doug McIlroy",
    "Fools ignore complexity. Pragmatists suffer it. Some can avoid it. Geniuses remove it. - Alan Perlis",
    "Progress is possible only if we train ourselves to think about programs without thinking of them as pieces of executable code. - Edsger W. Dijkstra",
    "The cheapest, fastest, and most reliable components are those that aren’t there. - Gordon Bell",
    "Programming can be fun, so can cryptography; however, they should not be combined. - Kreitzberg and Shneiderman",
    "There are only two kinds of programming languages: those people always complain about and those nobody uses. - Bjarne Stroustrup",
    "Programs should be written and polished until they acquire publication quality. - Niklaus Wirth",
    "The best way to predict the future is to invent it. - Alan Kay",
    "The only true measure of code quality: WTFs/minute. - Anonymous",
    "Software and cathedrals are much the same – first we build them, then we pray. - Anonymous",
    "When a program is being tested, it is too late to make design changes. - Anonymous",
    "Documentation is a love letter that you write to your future self. - Damian Conway",
    "The faster you can get your ideas to feedback, the more likely you are to learn something useful. - John Carmack",
    "Programming is not easy like Sunday morning, it’s more like Saturday night. - Anonymous",
    "The proper use of comments is to compensate for our failure to express ourself in code. - Robert C. Martin",
    "Good code is its own best documentation. - Steve McConnell",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. - Niklaus Wirth",
    "It is not enough for code to work. - Robert C. Martin",
    "I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing. - Oktal",
    "Learning to program has no more to do with designing interactive software than learning to touch type has to do with writing poetry. - Ted Nelson",
    "The purpose of software engineering is to control complexity, not to create it. - Pamela Zave",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "When debugging, novices insert corrective code; experts remove defective code. - Richard Pattis",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements. - Brian Kernighan",
    "A language that doesn’t affect the way you think about programming is not worth knowing. - Alan Perlis",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - Rick Osborne",
    "Good judgment comes from experience, and experience comes from bad judgment. - Fred Brooks",
    "First, solve the problem. Then, write the code. - John Johnson",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "Deleted code is debugged code. - Jeff Sickel",
    "In order to be irreplaceable, one must always be different. - Coco Chanel",
    "If you think your users are idiots, only idiots will use it. - Linus Torvalds",
    "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. - C.A.R. Hoare",
    "Programmers are tools for converting caffeine into code. - Anonymous",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "Good code is its own best documentation. - Steve McConnell",
    "When to use iterative development? You should use iterative development only on projects that you want to succeed. - Martin Fowler",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "The best way to predict the future is to invent it. - Alan Kay",
    "In programming the hard part isn’t solving problems, but deciding what problems to solve. - Paul Graham",
    "The only way to learn a new programming language is by writing programs in it. - Dennis Ritchie",
    "The purpose of software engineering is to control complexity, not to create it. - Pamela Zave",
    "Deleted code is debugged code. - Jeff Sickel",
    "The key to performance is elegance, not battalions of special cases. - Jon Bentley and Doug McIlroy",
    "It is not enough for code to work. - Robert C. Martin",
    "Good judgment comes from experience, and experience comes from bad judgment. - Fred Brooks",
    "Truth can only be found in one place: the code. - Robert C. Martin",
    "The proper use of comments is to compensate for our failure to express ourself in code. - Robert C. Martin",
    "In programming the hard part isn’t solving problems, but deciding what problems to solve. - Paul Graham",
    "Simplicity is prerequisite for reliability. - Edsger W. Dijkstra",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. - Niklaus Wirth",
    "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies. - C.A.R. Hoare",
    "The only true measure of code quality: WTFs/minute. - Anonymous",
    "Deleted code is debugged code. - Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. - Cory House",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "A language that doesn’t affect the way you think about programming is not worth knowing. - Alan Perlis",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "Deleted code is debugged code. - Jeff Sickel",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "It is not enough for code to work. - Robert C. Martin",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "The purpose of software engineering is to control complexity, not to create it. - Pamela Zave",
    "The best way to predict the future is to invent it. - Alan Kay",
    "If you think your users are idiots, only idiots will use it. - Linus Torvalds",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "Simplicity is the soul of efficiency. - Austin Freeman",
    "In programming the hard part isn’t solving problems, but deciding what problems to solve. - Paul Graham",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "Deleted code is debugged code. - Jeff Sickel",
    "Good code is its own best documentation. - Steve McConnell",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. - Niklaus Wirth",
    "It is not enough for code to work. - Robert C. Martin",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "The only way to learn a new programming language is by writing programs in it. - Dennis Ritchie",
    "The proper use of comments is to compensate for our failure to express ourself in code. - Robert C. Martin",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "The key to performance is elegance, not battalions of special cases. - Jon Bentley and Doug McIlroy",
    "It is not enough for code to work. - Robert C. Martin",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. - Niklaus Wirth",
    "Deleted code is debugged code. - Jeff Sickel",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "If you think your users are idiots, only idiots will use it. - Linus Torvalds",
    "A language that doesn’t affect the way you think about programming is not worth knowing. - Alan Perlis",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "It is not enough for code to work. - Robert C. Martin",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "Good judgment comes from experience, and experience comes from bad judgment. - Fred Brooks",
    "Deleted code is debugged code. - Jeff Sickel",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "A language that doesn’t affect the way you think about programming is not worth knowing. - Alan Perlis",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "The purpose of software engineering is to control complexity, not to create it. - Pamela Zave",
    "Walking on water and developing software from a specification are easy if both are frozen. - Edward V. Berard",
    "It is not enough for code to work. - Robert C. Martin",
    "Good judgment comes from experience, and experience comes from bad judgment. - Fred Brooks",
    "Deleted code is debugged code. - Jeff Sickel",
    "The best way to predict the future is to invent it. - Alan Kay",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want. - Niklaus Wirth",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
    "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
    "The key to performance is elegance, not battalions of special cases. - Jon Bentley and Doug McIlroy",
    "The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout",
    "It is not enough for code to work. - Robert C. Martin",
    "A language that doesn’t affect the way you think about programming is not worth knowing. - Alan Perlis",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in. - Edsger Dijkstra",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous",
    "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson"
  ];

  
  function generateQuote() {
    // Generate a random number between 0 and the number of quotes
    const randomIndex = Math.floor(Math.random() * quotes.length);
    
    // Get the quote at the random index
    const randomQuote = quotes[randomIndex];
    
    // Display the quote on the page
    document.getElementById('quote').innerText = randomQuote;
}